# Generated by Django 4.2.10 on 2024-02-19 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dancer',
            fields=[
                ('dancer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'books',
                'managed': True,
            },
        ),
    ]
